name: yoloanomalibhub
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - flask==3.1.2
      - torch==2.8.0+cpu
      - torchvision==0.23.0+cpu
      - pytorch-lightning==2.4.0
      - anomalib==2.1.0
      - ultralytics==8.3.202
      - ultralytics-thop==2.0.17
      - open-clip-torch==3.1.0
      - torchmetrics==1.8.2
      - python-dotenv==1.1.1
      - pandas==2.3.2
      - numpy==2.2.6
      - pillow==11.3.0
      - requests==2.32.5
      - pyyaml==6.0.2
      - tqdm==4.67.1
      - fsspec==2025.9.0
      - filelock==3.19.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - networkx==3.4.2
      - psutil==7.1.0
      - polars==1.33.1
      - matplotlib==3.10.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.60.0
      - kiwisolver==1.4.9
      - python-dateutil==2.9.0.post0
      - packaging==25.0
      - importlib-resources==6.5.2
      - lazy-loader==0.4
      - jsonargparse==4.41.0
      - omegaconf==2.3.0
      - rich==14.1.0
      - rich-argparse==1.7.1
      - huggingface-hub==0.35.0
      - safetensors==0.6.2
      - hf-xet==1.1.10
      - ftfy==6.3.1
      - sympy==1.14.0
      - mpmath==1.3.0
      - opencv-python==4.12.0.88
      - tzdata==2025.2
variables:
  PYTHONNOUSERSITE: "1"
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
