name: anomalib
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.8.0+cpu
      - torchvision==0.23.0+cpu
      - pytorch-lightning==2.4.0
      - anomalib==2.1.0
      - ultralytics==8.3.202
      - open-clip-torch==3.1.0
      - python-dotenv==1.1.1
      - pandas==2.3.2
      - pillow==11.3.0
      - requests==2.32.5
      - pyyaml==6.0.2
      - tqdm==4.67.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - opencv-python==4.12.0.88
      - matplotlib==3.10.6
variables:
  PYTHONNOUSERSITE: "1"
  PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
